spring.application.name=order-management
spring.datasource.url=jdbc:postgresql://localhost:5432/ordermanagement_db
spring.datasource.username=lukii
spring.datasource.password=277353
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update